# Generated by Django 5.2.15 on 2026-08-31 09:24

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tripadvisor', 'TripAdvisor'), ('google', 'Google'), ('facebook', 'Facebook'), ('other', 'Other')], default='tripadvisor', max_length=20)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_location', models.CharField(blank=True, max_length=100)),
                ('reviewer_avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('review_date', models.DateField(help_text='Date the review was originally posted on the source platform')),
                ('source_url', models.URLField(blank=True, help_text='Link to the original review on TripAdvisor/Google', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, help_text='Leave blank for general company reviews', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_reviews', to='tours.tour')),
            ],
            options={
                'verbose_name': 'External Review',
                'verbose_name_plural': 'External Reviews',
                'db_table': 'external_reviews',
                'ordering': ['order', '-review_date'],
                'indexes': [models.Index(fields=['tour', 'is_active'], name='extreview_tour_idx'), models.Index(fields=['source', 'is_active'], name='extreview_source_idx'), models.Index(fields=['is_featured'], name='extreview_featured_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('travel_date', models.DateField(blank=True, help_text='Month/year of the actual trip', null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True, help_text='Optional public response from safari pro team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, help_text='Links review to a completed booking — ensures verified status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='booking.booking')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_reviews', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Review',
                'verbose_name_plural': 'Tour Reviews',
                'db_table': 'tour_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tour', 'is_approved'], name='review_tour_approved_idx'), models.Index(fields=['is_featured'], name='review_featured_idx')],
            },
        ),
    ]
