version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/tools/api-types"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tools/healthcheck"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/tools/envcheck"
    schedule:
      interval: "weekly"
