# Generated by Django 5.2.15 on 2026-08-31 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('booked', 'Booked'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('ai_plan', models.JSONField(blank=True, default=dict, help_text='Full AI-generated day-by-day plan stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tours', models.ManyToManyField(blank=True, related_name='custom_itineraries', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Itinerary',
                'verbose_name_plural': 'Custom Itineraries',
                'db_table': 'custom_itineraries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
