# Generated by Django 5.2.15 on 2026-08-31 09:24

import apps.core.validators
import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Exclusions',
                'db_table': 'exclusions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name e.g. 'utensils', 'shield', 'user'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Inclusions',
                'db_table': 'inclusions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'db_table': 'tour_itinerary',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tour Categories',
                'db_table': 'tour_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='SEO copy shown on the tag landing page (/tours/tag/slug/)')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('topic_pillar', models.CharField(choices=[('route', 'Kilimanjaro Route'), ('destination', 'Destination / Park'), ('activity', 'Activity Type'), ('difficulty', 'Difficulty Level'), ('season', 'Season / Timing'), ('wildlife', 'Wildlife'), ('accommodation', 'Accommodation'), ('general', 'General')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tag_slug_idx'), models.Index(fields=['topic_pillar'], name='tag_pillar_idx'), models.Index(fields=['is_active'], name='tag_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Keep under 60 chars for best SERP display.', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tour_type', models.CharField(choices=[('multi_day_trek', 'Multi-Day Trek'), ('day_trip', 'Day Trip'), ('safari', 'Safari'), ('beach', 'Beach'), ('combo', 'Combo Package')], default='multi_day_trek', max_length=20)),
                ('place_name', models.CharField(help_text='e.g. Mount Kilimanjaro, Serengeti National Park', max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Full tour description — used as fallback if no content blocks exist.')),
                ('excerpt', models.TextField(blank=True, help_text='150–300 chars. Used in cards and meta description fallback.', max_length=300)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='% deposit required. Default 10% for treks, 100% for day trips.', max_digits=5)),
                ('lodge_level', models.CharField(blank=True, choices=[('basic', 'Basic / Camping'), ('mid_range', 'Mid-Range Lodge'), ('luxury', 'Luxury'), ('ultra_lux', 'Ultra-Luxury / Signature')], help_text='For Safari tours: Define the comfort level.', max_length=20, null=True)),
                ('beach_type', models.CharField(blank=True, choices=[('relax', 'Relaxation'), ('adventure', 'Water Sports / Adventure'), ('honeymoon', 'Honeymoon / Romantic')], help_text='For Beach tours: Define the vacation style.', max_length=20, null=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], max_length=20)),
                ('max_altitude', models.CharField(blank=True, max_length=100)),
                ('group_size', models.CharField(blank=True, max_length=50)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('feature_image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload a high-quality hero image. • Max file size: 5 MB\n• Formats: JPG, JPEG, PNG, WEBP\n• Tip: Use WebP for 30-50% smaller files.', max_length=255, null=True, validators=[apps.core.validators.validate_image_size, apps.core.validators.validate_image_format], verbose_name='image')),
                ('image_alt_text', models.CharField(blank=True, max_length=150)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('secondary_keywords', models.CharField(blank=True, help_text="Comma-separated LSI keywords e.g. 'safari lodges, best time for safari'", max_length=300)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=95)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.core.validators.validate_image_size, apps.core.validators.validate_image_format], verbose_name='image')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', max_length=50)),
                ('schema_type', models.CharField(choices=[('TouristTrip', 'Tourist Trip'), ('Product', 'Product'), ('Event', 'Event')], default='TouristTrip', max_length=50)),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Extra JSON-LD fields merged into schema output.')),
                ('seo_priority', models.PositiveIntegerField(default=5, help_text='1=low, 10=critical — used for sitemap priority', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('last_seo_audit', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='Last time Google Indexing API was pinged for this URL', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exclusions', models.ManyToManyField(blank=True, related_name='tours', to='tours.exclusion')),
                ('inclusions', models.ManyToManyField(blank=True, related_name='tours', to='tours.inclusion')),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.itinerary')),
                ('tags', models.ManyToManyField(blank=True, related_name='tours', to='tours.tag')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcategory')),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading (H2)'), ('subheading', 'Subheading (H3)'), ('paragraph', 'Paragraph'), ('faq', 'FAQ Item'), ('highlight_box', 'Highlight Box'), ('cta_block', 'Call-to-Action Block'), ('list', 'Bullet List'), ('quote', 'Pull Quote')], default='paragraph', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('anchor_id', models.SlugField(blank=True, help_text='Auto-generated from heading for TOC links', max_length=80)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('include_in_toc', models.BooleanField(default=True, help_text='Include this heading in the table of contents')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_content_blocks',
                'ordering': ['tour', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Upload a high-quality hero image. • Max file size: 5 MB\n• Formats: JPG, JPEG, PNG, WEBP\n• Tip: Use WebP for 30-50% smaller files.', max_length=255, validators=[apps.core.validators.validate_image_size, apps.core.validators.validate_image_format], verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_hero', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_images',
                'ordering': ['tour', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day number (1,2,3…) or 0 for time-based day trips')),
                ('time', models.CharField(blank=True, help_text="e.g. '08:00 AM' — for day trips only", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tours.itinerary')),
                ('tags', models.ManyToManyField(blank=True, related_name='itinerary_items', to='tours.tag')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary Items',
                'db_table': 'itinerary_items',
                'ordering': ['order', 'day_number', 'time'],
                'unique_together': {('itinerary', 'day_number', 'time')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('month_end', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('rating', models.CharField(choices=[('best', 'Best Season'), ('good', 'Good'), ('possible', 'Possible'), ('avoid', 'Avoid')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_windows', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_seasonal_windows',
                'ordering': ['tour', 'month_start'],
                'indexes': [models.Index(fields=['tour'], name='seasonal_tour_idx'), models.Index(fields=['month_start'], name='seasonal_month_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComboPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('schema_type', models.CharField(default='TouristTrip', max_length=50)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='combo_packages', to='tours.tag')),
                ('tours', models.ManyToManyField(blank=True, related_name='combo_packages', to='tours.tour')),
            ],
            options={
                'db_table': 'combo_packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='combo_slug_idx'), models.Index(fields=['is_active'], name='combo_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sold_out', 'Sold Out'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availabilities', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Availability',
                'verbose_name_plural': 'Tour Availabilities',
                'db_table': 'tour_availability',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['tour', 'status'], name='avail_tour_status_idx'), models.Index(fields=['start_date', 'status'], name='avail_date_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['slug'], name='tour_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', 'is_featured'], name='tour_active_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['category', 'is_active'], name='tour_category_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['tour_type'], name='tour_type_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price_usd'], name='tour_price_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['duration_days'], name='tour_duration_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['focus_keyword'], name='tour_focus_keyword_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', 'focus_keyword'], name='tour_active_focus_idx'),
        ),
        migrations.AddIndex(
            model_name='tourcontentblock',
            index=models.Index(fields=['tour', 'order'], name='contentblock_tour_order_idx'),
        ),
        migrations.AddIndex(
            model_name='tourimage',
            index=models.Index(fields=['tour'], name='tourimage_tour_idx'),
        ),
        migrations.AddIndex(
            model_name='tourimage',
            index=models.Index(fields=['is_hero'], name='tourimage_hero_idx'),
        ),
    ]
