# Generated by Django 5.2.15 on 2026-08-31 09:24

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name e.g. 'mountain', 'backpack'", max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Guide Categories',
                'db_table': 'guide_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrekGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Keep 55–60 chars for best SERP display', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('first_paragraph', models.TextField(blank=True, help_text='Opening paragraph shown below the title. CRITICAL for SEO — include focus keyword naturally. Google uses this to understand page entity and topic.')),
                ('excerpt', models.TextField(blank=True, help_text='155–300 chars. Used in cards, meta description fallback, and related content previews.', max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Full guide body. first_paragraph is rendered separately above this.')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword — should appear in title, first_paragraph, and meta_description', max_length=100)),
                ('secondary_keywords', models.CharField(blank=True, help_text="Comma-separated secondary/LSI keywords e.g. 'machame route map, machame route distance'", max_length=300)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=95)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('HowTo', 'How-To Guide'), ('FAQPage', 'FAQ Page'), ('BlogPosting', 'Blog Post')], default='Article', max_length=50)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_alt_text', models.CharField(blank=True, max_length=150)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Auto-calculated. Minutes to read.')),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='Last Google Indexing API ping', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trek_guides', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='guide.guidecategory')),
                ('primary_tour', models.ForeignKey(blank=True, help_text='The single most relevant tour for this guide. Used for the main booking CTA and canonical cross-link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_guides', to='tours.tour')),
                ('related_tours', models.ManyToManyField(blank=True, help_text='Tours directly related to this guide — shown as CTAs at bottom of guide', related_name='related_guides', to='tours.tour')),
                ('tags', models.ManyToManyField(blank=True, help_text="Shared tags with Tour model — creates topic cluster mesh. e.g. tag 'machame-route' links this guide to all Machame tours.", related_name='trek_guides', to='tours.tag')),
            ],
            options={
                'verbose_name': 'Trek Guide',
                'verbose_name_plural': 'Trek Guides',
                'db_table': 'trek_guides',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='GuideInternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_url', models.URLField(blank=True, help_text='External URL only if not linking to a guide or tour', max_length=500)),
                ('anchor_text', models.CharField(help_text='Visible link text — include target keyword for SEO value', max_length=200)),
                ('link_type', models.CharField(choices=[('related', 'Related Guide'), ('prerequisite', 'Prerequisite Reading'), ('next_step', 'Next Step'), ('detailed', 'More Details'), ('tour', 'Related Tour')], default='related', max_length=20)),
                ('is_nofollow', models.BooleanField(default=False, help_text="Add rel='nofollow' — use for external/affiliate links only")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_tour', models.ForeignKey(blank=True, help_text='Link directly to a tour product page — guide → tour backlink', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_links', to='tours.tour')),
                ('from_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='guide.trekguide')),
                ('to_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='guide.trekguide')),
            ],
            options={
                'verbose_name': 'Guide Internal Link',
                'verbose_name_plural': 'Guide Internal Links',
                'db_table': 'guide_internal_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading (H2)'), ('subheading', 'Subheading (H3)'), ('paragraph', 'Paragraph'), ('list', 'Bullet List'), ('numbered_list', 'Numbered List'), ('quote', 'Pull Quote'), ('warning', 'Warning / Alert'), ('info', 'Info Box'), ('checklist', 'Checklist'), ('faq', 'FAQ Item'), ('highlight_box', 'Highlight Box'), ('cta_block', 'Call-to-Action Block')], default='paragraph', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('include_in_toc', models.BooleanField(default=True)),
                ('anchor_id', models.SlugField(blank=True, max_length=100)),
                ('focus_keyword', models.CharField(blank=True, help_text='Target keyword for this specific section — aids semantic SEO', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name for this block', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='guide.trekguide')),
            ],
            options={
                'verbose_name': 'Guide Content Block',
                'verbose_name_plural': 'Guide Content Blocks',
                'db_table': 'guide_content_blocks',
                'ordering': ['guide', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('first_paragraph', models.TextField(blank=True, help_text='Opening paragraph — rendered prominently above main content. Include focus keyword naturally. Critical for Google entity understanding.')),
                ('excerpt', models.TextField(blank=True, help_text='Used in article cards, meta description fallback, and related content previews.', max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=155)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('secondary_keywords', models.CharField(blank=True, help_text='Comma-separated LSI keywords', max_length=300)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=95)),
                ('og_description', models.TextField(blank=True, max_length=200)),
                ('og_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('schema_type', models.CharField(choices=[('BlogPosting', 'Blog Post'), ('Article', 'Article'), ('NewsArticle', 'News Article')], default='BlogPosting', max_length=50)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_alt_text', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=5)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_articles', to=settings.AUTH_USER_MODEL)),
                ('primary_tour', models.ForeignKey(blank=True, help_text='Main tour CTA shown at end of article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='tours.tour')),
                ('related_tours', models.ManyToManyField(blank=True, help_text='Tours mentioned or relevant to this article — renders as related CTAs', related_name='blog_articles', to='tours.tour')),
                ('tags', models.ManyToManyField(blank=True, help_text='Shared tag taxonomy with tours and guides — topic cluster foundation', related_name='blog_articles', to='tours.tag')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='guide.guidecategory')),
                ('related_guides', models.ManyToManyField(blank=True, help_text="Trek guides to show as 'Further Reading' — strengthens internal mesh", related_name='related_articles', to='guide.trekguide')),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
                'db_table': 'blog_articles',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddIndex(
            model_name='trekguide',
            index=models.Index(fields=['slug'], name='guide_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='trekguide',
            index=models.Index(fields=['is_published', 'is_featured'], name='guide_pub_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='trekguide',
            index=models.Index(fields=['category', 'is_published'], name='guide_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='trekguide',
            index=models.Index(fields=['publish_date'], name='guide_date_idx'),
        ),
        migrations.AddIndex(
            model_name='guideinternallink',
            index=models.Index(fields=['from_guide', 'is_active'], name='glink_from_active_idx'),
        ),
        migrations.AddIndex(
            model_name='guideinternallink',
            index=models.Index(fields=['to_guide'], name='glink_to_guide_idx'),
        ),
        migrations.AddIndex(
            model_name='guideinternallink',
            index=models.Index(fields=['to_tour'], name='glink_to_tour_idx'),
        ),
        migrations.AddIndex(
            model_name='guidecontentblock',
            index=models.Index(fields=['guide', 'order'], name='guideblock_guide_order_idx'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['slug'], name='article_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['status', 'publish_date'], name='article_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['category', 'status'], name='article_cat_status_idx'),
        ),
    ]
