# Generated by Django 5.2.15 on 2026-08-31 09:24

import cloudinary.models
import cloudinary_storage.storage
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_from', models.CharField(blank=True, max_length=40)),
                ('date_to', models.CharField(blank=True, max_length=40)),
                ('group_size', models.CharField(blank=True, max_length=40)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('department', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('full_time', 'Full time'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('location', models.CharField(default='Moshi, Tanzania', max_length=120)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VISIT KILI ADVNTURES', max_length=100)),
                ('contact_email', models.EmailField(default='info@safari pro.com', max_length=254)),
                ('contact_phone', models.CharField(default='+255...', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('office_address', models.TextField(blank=True)),
                ('show_announcement', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, max_length=255)),
                ('announcement_link', models.URLField(blank=True)),
                ('holiday_mode', models.BooleanField(default=False, help_text='Enable for special UI themes (e.g. Eid, Christmas)')),
                ('holiday_name', models.CharField(blank=True, help_text='e.g. Eid Mubarak', max_length=50)),
                ('default_meta_title', models.CharField(blank=True, max_length=60)),
                ('default_meta_description', models.CharField(blank=True, max_length=155)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('linkedin', models.URLField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('summits_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='careers/cv/')),
                ('cover_letter', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
