# Generated by Django 5.2.15 on 2026-08-31 09:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Destination Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(help_text='For list views and meta descriptions.')),
                ('description', models.TextField(help_text='Main content, supports HTML/Safe.')),
                ('feature_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('location_name', models.CharField(blank=True, help_text='e.g. Serengeti National Park, Tanzania', max_length=200)),
                ('altitude', models.CharField(blank=True, max_length=50)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='Last time Google Indexing API was pinged for this URL', null=True)),
                ('related_articles', models.ManyToManyField(blank=True, related_name='mentioned_in_destinations', to='guide.blogarticle')),
                ('related_guides', models.ManyToManyField(blank=True, related_name='mentioned_in_destinations', to='guide.trekguide')),
                ('related_tours', models.ManyToManyField(blank=True, related_name='mentioned_in_destinations', to='tours.tour')),
                ('tags', models.ManyToManyField(blank=True, to='tours.tag')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='destinations.destinationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='destinations.destination')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DestinationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.destination')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
