# Generated by Django 5.2.15 on 2026-08-31 09:24

import apps.booking.models
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('topic', models.CharField(choices=[('kilimanjaro', 'Kilimanjaro Climbing'), ('safari', 'Safari'), ('zanzibar', 'Zanzibar Beach'), ('day_trip', 'Day Trip'), ('group', 'Group Tour'), ('custom', 'Custom Itinerary'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'db_table': 'contact_enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(default=apps.booking.models.generate_booking_ref, editable=False, help_text='Human-readable reference e.g. SA3F9B2C', max_length=12, unique=True)),
                ('secure_token', models.CharField(db_index=True, default=apps.booking.models.generate_secure_token, editable=False, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('whatsapp_number', models.CharField(blank=True, help_text='If different from phone', max_length=25)),
                ('country', django_countries.fields.CountryField(default='TZ', max_length=2)),
                ('num_people', models.PositiveIntegerField(default=1)),
                ('travel_date', models.DateField()),
                ('flexible_dates', models.BooleanField(default=False, help_text='Client is flexible on the exact travel date')),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone Call')], default='whatsapp', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner — first trek'), ('intermediate', 'Intermediate — some hiking experience'), ('experienced', 'Experienced — regular hiker'), ('advanced', 'Advanced — high altitude experience')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Special requests, dietary needs, accommodation preferences, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes — not visible to client')),
                ('quoted_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price in USD — fill before generating DPO link', max_digits=10, null=True)),
                ('dpo_payment_url', models.URLField(blank=True, help_text='Custom DPO payment URL to send to client')),
                ('dpo_payment_url_sent', models.BooleanField(default=False, help_text='Has the DPO link been sent to the client?')),
                ('payment_confirmed', models.BooleanField(default=False, help_text='Tick once DPO payment is confirmed by staff')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member handling this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('min_participants', models.PositiveIntegerField(default=2)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('open', 'Open for Bookings'), ('filling', 'Filling Fast'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Deadline — no new join requests after this date')),
                ('feature_badge', models.CharField(blank=True, choices=[('hot', 'Hot Deal'), ('last_chance', 'Last Chance'), ('almost_full', 'Almost Full'), ('confirmed', 'Confirmed'), ('new', 'New')], max_length=20)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('benefits_text', models.TextField(blank=True, help_text="e.g. 'Free airport transfer from Arusha'")),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departures', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_departures', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Group Departure',
                'verbose_name_plural': 'Group Departures',
                'db_table': 'group_departures',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, editable=False, help_text='Auto-generated reference e.g. SAGM3F9B', max_length=12, unique=True)),
                ('secure_token', models.CharField(db_index=True, default=apps.booking.models.generate_secure_token, editable=False, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('whatsapp_number', models.CharField(blank=True, help_text='If different from phone — staff will use this for payment link', max_length=25)),
                ('country', django_countries.fields.CountryField(default='TZ', max_length=2)),
                ('party_size', models.PositiveIntegerField(default=1, help_text='Number of people in this party')),
                ('message', models.TextField(blank=True, help_text='Special requests, dietary needs, experience level, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes — not visible to client')),
                ('dpo_payment_url', models.URLField(blank=True, help_text='Custom DPO payment URL — staff generate and send to client')),
                ('payment_confirmed', models.BooleanField(default=False, help_text='Staff manually tick once DPO payment is confirmed')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='booking.groupdeparture')),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_group_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'db_table': 'group_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dpo_reference', models.CharField(blank=True, help_text='DPO transaction reference from the DPO dashboard', max_length=100)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. Visa, M-Pesa, bank transfer', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='booking.booking')),
                ('group_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='booking.groupmember')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ref'], name='booking_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour', 'status'], name='booking_tour_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['travel_date'], name='booking_travel_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'payment_confirmed'], name='booking_status_pay_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['email'], name='booking_email_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdeparture',
            index=models.Index(fields=['tour', 'status', 'is_active'], name='gdep_tour_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdeparture',
            index=models.Index(fields=['start_date', 'status'], name='gdep_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdeparture',
            index=models.Index(fields=['expires_at', 'status'], name='gdep_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'status'], name='gmember_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['email'], name='gmember_email_idx'),
        ),
    ]
