/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 *
 * COMMITTED TO GIT (unusual for a generated file): `payload generate:types`
 * currently crashes in this dev environment (ERR_REQUIRE_ASYNC_MODULE, a
 * tsx/Payload ESM-CJS interop issue — see ruffle.md's "TOOLING BLOCKER").
 * Until that's fixed, this file is hand-maintained to match payload.config.ts
 * and checked in so a fresh clone (e.g. the deploy VPS) doesn't need
 * generate:types to succeed just to get a working build. If you fix the
 * tooling, regenerate this normally and it'll just overwrite these hand
 * edits — safe either way.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tours: Tour;
    categories: Category;
    guides: Guide;
    articles: Article;
    tags: Tag;
    reviews: Review;
    'legal-pages': LegalPage;
    media: Media;
    users: User;
    inquiries: Inquiry;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tours: ToursSelect<false> | ToursSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  title: string;
  /**
   * Permanent once published — never regenerate after indexing, even if title changes.
   */
  slug: string;
  category: number | Category;
  durationDays?: number | null;
  /**
   * Display-only "from" price. Not a transactable amount — no payment flow attached.
   */
  priceFrom?: number | null;
  groupSize?: {
    min?: number | null;
    max?: number | null;
  };
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        day: number;
        title: string;
        description?: string | null;
        /**
         * Feeds the MapLibre route on the tour detail page.
         */
        location?: {
          lat?: number | null;
          lng?: number | null;
          name?: string | null;
        };
        activities?:
          | {
              activity: string;
              id?: string | null;
            }[]
          | null;
        accommodation?: string | null;
        meals?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as FAQPage schema on the detail page.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  promoSuperTitle?: string | null;
  promoTitle?: string | null;
  promoSubtitle?: string | null;
  oldPrice?: number | null;
  discountTitle?: string | null;
  departureLocation?: string | null;
  returnLocation?: string | null;
  bookingLinkOverride?: string | null;
  priceIncludes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  priceExcludes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  isEverydayTour?: boolean | null;
  everydayStartTime?: string | null;
  startDates?:
    | {
        date: string;
        time?: string | null;
        id?: string | null;
      }[]
    | null;
  additionalPrices?:
    | {
        title: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  additionalInfoItems?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  complementaries?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  mapEmbedUrl?: string | null;
  customTabTitle?: string | null;
  customTabContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  moreInfo?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 155–300 characters. Falls back to meta description if none is set below.
   */
  excerpt?: string | null;
  /**
   * Rendered prominently at the top of the page. This is the entity-context paragraph search engines read first to understand what the page is about — write it like a definition, not a hook.
   */
  firstParagraph: string;
  /**
   * Drives the /topic/[slug] mesh hub — every tagged item surfaces there automatically.
   */
  tags?: (number | Tag)[] | null;
  focusKeyword?: string | null;
  /**
   * Comma-separated LSI terms.
   */
  secondaryKeywords?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  canonicalUrl?: string | null;
  ogImage?: (number | null) | Media;
  schemaType?: ('TouristTrip' | 'Article' | 'FAQPage' | 'LocalBusiness' | 'none') | null;
  /**
   * Sitemap priority weight (0–1).
   */
  seoPriority?: number | null;
  /**
   * Set automatically when the search-engine ping job fires.
   */
  lastIndexedAt?: string | null;
  isActive?: boolean | null;
  publishDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Permanent once published — never regenerate after indexing, even if name changes.
   */
  slug: string;
  description?: string | null;
  heroImage?: (number | null) | Media;
  tags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The mesh hub layer. Every tag renders a /topic/[slug] page pulling in all tagged Tours, Guides, and Articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Permanent once published — never regenerate after indexing, even if name changes.
   */
  slug: string;
  description?: string | null;
  /**
   * Used to group related topics on the hub page.
   */
  category?: ('route' | 'destination' | 'season' | 'activity' | 'group-size' | 'comparison') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  /**
   * Permanent once published — never regenerate after indexing, even if title changes.
   */
  slug: string;
  guideType?: ('pillar' | 'cluster') | null;
  /**
   * The "book this" CTA target for this guide.
   */
  primaryTour?: (number | null) | Tour;
  relatedTours?: (number | Tour)[] | null;
  relatedGuides?: (number | Guide)[] | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 155–300 characters. Falls back to meta description if none is set below.
   */
  excerpt?: string | null;
  /**
   * Rendered prominently at the top of the page. This is the entity-context paragraph search engines read first to understand what the page is about — write it like a definition, not a hook.
   */
  firstParagraph: string;
  /**
   * Drives the /topic/[slug] mesh hub — every tagged item surfaces there automatically.
   */
  tags?: (number | Tag)[] | null;
  focusKeyword?: string | null;
  /**
   * Comma-separated LSI terms.
   */
  secondaryKeywords?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  canonicalUrl?: string | null;
  ogImage?: (number | null) | Media;
  schemaType?: ('TouristTrip' | 'Article' | 'FAQPage' | 'LocalBusiness' | 'none') | null;
  /**
   * Sitemap priority weight (0–1).
   */
  seoPriority?: number | null;
  /**
   * Set automatically when the search-engine ping job fires.
   */
  lastIndexedAt?: string | null;
  publishDate?: string | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Permanent once published — never regenerate after indexing, even if title changes.
   */
  slug: string;
  author?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedTours?: (number | Tour)[] | null;
  relatedGuides?: (number | Guide)[] | null;
  /**
   * 155–300 characters. Falls back to meta description if none is set below.
   */
  excerpt?: string | null;
  /**
   * Rendered prominently at the top of the page. This is the entity-context paragraph search engines read first to understand what the page is about — write it like a definition, not a hook.
   */
  firstParagraph: string;
  /**
   * Drives the /topic/[slug] mesh hub — every tagged item surfaces there automatically.
   */
  tags?: (number | Tag)[] | null;
  focusKeyword?: string | null;
  /**
   * Comma-separated LSI terms.
   */
  secondaryKeywords?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  canonicalUrl?: string | null;
  ogImage?: (number | null) | Media;
  schemaType?: ('TouristTrip' | 'Article' | 'FAQPage' | 'LocalBusiness' | 'none') | null;
  /**
   * Sitemap priority weight (0–1).
   */
  seoPriority?: number | null;
  /**
   * Set automatically when the search-engine ping job fires.
   */
  lastIndexedAt?: string | null;
  publishDate?: string | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug:
    | 'terms-and-conditions'
    | 'cookies-policy'
    | 'privacy-policy'
    | 'refund-policy'
    | 'editorial-policy'
    | 'sustainability-policy';
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Review {
  id: number;
  authorName: string;
  authorCountry?: string | null;
  rating: number;
  body: string;
  source: 'direct' | 'tripadvisor' | 'google' | 'safaribookings';
  /**
   * Link to the original review, if imported.
   */
  sourceUrl?: string | null;
  tour?: (number | null) | Tour;
  reviewDate?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Every submission from the hardcoded Contact/Booking pages — no
 * CMS-configurable form builder, just a plain collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  source: 'contact' | 'booking';
  name: string;
  email: string;
  whatsapp?: string | null;
  tour?: (number | null) | Tour;
  preferredDate?: string | null;
  travelers?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Background image for the homepage hero. Falls back to a stock photo if unset.
   */
  homeHeroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  durationDays?: T;
  priceFrom?: T;
  groupSize?:
    | T
    | {
        min?: T;
        max?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        description?: T;
        location?:
          | T
          | {
              lat?: T;
              lng?: T;
              name?: T;
            };
        activities?:
          | T
          | {
              activity?: T;
              id?: T;
            };
        accommodation?: T;
        meals?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  content?: T;
  excerpt?: T;
  firstParagraph?: T;
  tags?: T;
  focusKeyword?: T;
  secondaryKeywords?: T;
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  ogImage?: T;
  schemaType?: T;
  seoPriority?: T;
  lastIndexedAt?: T;
  isActive?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  guideType?: T;
  primaryTour?: T;
  relatedTours?: T;
  relatedGuides?: T;
  heroImage?: T;
  content?: T;
  excerpt?: T;
  firstParagraph?: T;
  tags?: T;
  focusKeyword?: T;
  secondaryKeywords?: T;
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  ogImage?: T;
  schemaType?: T;
  seoPriority?: T;
  lastIndexedAt?: T;
  publishDate?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  heroImage?: T;
  content?: T;
  relatedTours?: T;
  relatedGuides?: T;
  excerpt?: T;
  firstParagraph?: T;
  tags?: T;
  focusKeyword?: T;
  secondaryKeywords?: T;
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  ogImage?: T;
  schemaType?: T;
  seoPriority?: T;
  lastIndexedAt?: T;
  publishDate?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  authorName?: T;
  authorCountry?: T;
  rating?: T;
  body?: T;
  source?: T;
  sourceUrl?: T;
  tour?: T;
  reviewDate?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  source?: T;
  name?: T;
  email?: T;
  whatsapp?: T;
  tour?: T;
  preferredDate?: T;
  travelers?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  homeHeroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}